spring.datasource.url=jdbc:postgresql://localhost:5432/NamanSpring
spring.datasource.username=postgres
spring.datasource.password=naman@07
spring.datasource.driver-class-name=org.postgresql.Driver

# Run Schema.sql and Data.sql against non-embedded DBs during startup
spring.sql.init.mode=always
spring.sql.init.platform=postgresql
